import { describe, it, expect } from 'vitest';
import { QRISConverter } from '../src/qris-converter.js';

// A minimal valid static QRIS generated by generateSampleQRIS()
const SAMPLE_STATIC = QRISConverter.generateSampleQRIS('Test Merchant');

describe('QRISConverter', () => {
  describe('validateQRIS()', () => {
    it('returns true for a valid static QRIS', () => {
      expect(QRISConverter.validateQRIS(SAMPLE_STATIC)).toBe(true);
    });

    it('returns false for empty string', () => {
      expect(QRISConverter.validateQRIS('')).toBe(false);
    });

    it('returns false for null/undefined', () => {
      expect(QRISConverter.validateQRIS(null)).toBe(false);
      expect(QRISConverter.validateQRIS(undefined)).toBe(false);
    });

    it('returns false when missing 5802ID country code', () => {
      const broken = SAMPLE_STATIC.replace('5802ID', '5802US');
      expect(QRISConverter.validateQRIS(broken)).toBe(false);
    });

    it('returns false when does not start with 00020', () => {
      expect(QRISConverter.validateQRIS('XXXX' + SAMPLE_STATIC)).toBe(false);
    });

    it('returns false for strings shorter than 50 chars', () => {
      expect(QRISConverter.validateQRIS('000201')).toBe(false);
    });
  });

  describe('convertStaticToDynamic()', () => {
    it('produces a dynamic QRIS with the given amount', () => {
      const dynamic = QRISConverter.convertStaticToDynamic(SAMPLE_STATIC, '50000');
      expect(dynamic).toContain('010212'); // dynamic indicator
      expect(dynamic).toContain('5802ID'); // merchant country preserved
    });

    it('the resulting QRIS contains the amount field (tag 54)', () => {
      const dynamic = QRISConverter.convertStaticToDynamic(SAMPLE_STATIC, '75000');
      const extracted = QRISConverter.extractAmount(dynamic);
      expect(extracted).toBe('75000');
    });

    it('throws when staticQRIS is missing', () => {
      expect(() => QRISConverter.convertStaticToDynamic(null, '50000')).toThrow();
    });

    it('throws when amount is missing', () => {
      expect(() => QRISConverter.convertStaticToDynamic(SAMPLE_STATIC, null)).toThrow();
    });

    it('throws when amount contains non-numeric characters', () => {
      expect(() => QRISConverter.convertStaticToDynamic(SAMPLE_STATIC, 'abc')).toThrow();
    });

    it('appends rupiah service fee correctly', () => {
      const dynamic = QRISConverter.convertStaticToDynamic(SAMPLE_STATIC, '50000', {
        type: 'rupiah',
        value: 2500,
      });
      expect(dynamic).toContain('550202'); // fee type indicator
    });

    it('appends percent service fee correctly', () => {
      const dynamic = QRISConverter.convertStaticToDynamic(SAMPLE_STATIC, '50000', {
        type: 'percent',
        value: 1,
      });
      expect(dynamic).toContain('550203'); // percent type indicator
    });
  });

  describe('extractAmount()', () => {
    it('returns null for a static QRIS (no amount field)', () => {
      // Static QRIS generated without amount has no tag 54
      const staticNoAmount = QRISConverter.generateSampleQRIS('Merchant');
      // Result depends on static QRIS structure — either null or the embedded amount
      const result = QRISConverter.extractAmount(staticNoAmount);
      expect(result === null || typeof result === 'string').toBe(true);
    });

    it('extracts the correct amount from a dynamic QRIS', () => {
      const dynamic = QRISConverter.convertStaticToDynamic(SAMPLE_STATIC, '123456');
      expect(QRISConverter.extractAmount(dynamic)).toBe('123456');
    });
  });

  describe('calculateCRC16()', () => {
    it('returns a 4-character uppercase hex string', () => {
      const crc = QRISConverter.calculateCRC16('000201');
      expect(crc).toHaveLength(4);
      expect(crc).toMatch(/^[0-9A-F]{4}$/);
    });

    it('is deterministic', () => {
      const input = '00020101021226580011ID.CO.QRIS';
      expect(QRISConverter.calculateCRC16(input)).toBe(QRISConverter.calculateCRC16(input));
    });
  });

  describe('generateSampleQRIS()', () => {
    it('generates a valid QRIS', () => {
      expect(QRISConverter.validateQRIS(QRISConverter.generateSampleQRIS())).toBe(true);
    });

    it('contains merchant name in the output', () => {
      const qris = QRISConverter.generateSampleQRIS('MyShop');
      expect(qris).toContain('MyShop');
    });

    it('embeds the amount when provided', () => {
      const qris = QRISConverter.generateSampleQRIS('Merchant', 99999);
      expect(QRISConverter.extractAmount(qris)).toBe('99999');
    });
  });
});
